### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [moderndayandrew/prj-rev-bwfs-dasmoto#4]
Alternatively, you could use comma-separated selectors to specify shared properties for multiple elements:

```css
h1, h2, .price {
  font-weight:bold;
}
```

(Also see: #3)

https://github.com/moderndayandrew/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/Resources/style.css
